In [4]:
import numpy as np

# [4] Numpy: 통계

### [실습 1] 중심 경향 및 산포 측도 계산


아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.


```python
	arr = np.array([10, 20, 30, 30, 40, 50, 60])
```

In [14]:
arr = np.array([10, 20, 30, 30, 40, 50, 60])

values, counts = np.unique(arr, return_counts=True)

print(arr.mean())
print(np.median(arr))
print(values[np.argmax(counts)])
print(np.var(arr, ddof=0))
print(np.std(arr, ddof=0))
print(np.min(arr), "~", np.max(arr))


34.285714285714285
30.0
30
253.06122448979593
15.90789817951435
10 ~ 60


In [1]:
!pip install matplotlib

In [2]:
# 조금 자세히: Matplotlib은 기본 폰트가 한글을 지원하지 않아 경고가 날 수 있습니다.
# 운영체제별 후보 폰트 중 실제 설치된 폰트를 찾아 그래프 제목/축 라벨이 깨지지 않게 설정합니다.

import platform
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# Matplotlib 기본 폰트(DejaVu Sans)는 한글 글리프가 없어 경고가 날 수 있습니다.
# 운영체제별로 사용 가능한 한글 폰트를 찾아 설정합니다.
font_candidates = {
    "Darwin": ["AppleGothic", "NanumGothic", "Noto Sans CJK KR", "Noto Sans KR"],
    "Windows": ["Malgun Gothic", "NanumGothic", "Noto Sans CJK KR", "Noto Sans KR"],
    "Linux": ["NanumGothic", "Noto Sans CJK KR", "Noto Sans KR"],
}

available_fonts = {font.name for font in fm.fontManager.ttflist}
system_name = platform.system()
selected_font = None

for font_name in font_candidates.get(system_name, []):
    if font_name in available_fonts:
        selected_font = font_name
        break

if selected_font:
    plt.rcParams["font.family"] = selected_font
    print("설정된 한글 폰트:", selected_font)
else:
    print("사용 가능한 한글 폰트를 찾지 못했습니다. NanumGothic 또는 Noto Sans KR 설치가 필요할 수 있습니다.")

# 마이너스 기호가 깨지는 문제 방지
plt.rcParams["axes.unicode_minus"] = False

설정된 한글 폰트: Malgun Gothic


### [실습 2] 정규분포와 균등분포의 난수 생성


정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.

1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
2. 0과 1 사이의 균등분포 난수 1000개 생성

In [12]:
arr1 = np.random.normal(loc = 0, scale = 1, size = 1000)

print(arr1)

print(arr1.mean())
print(np.std(arr1, ddof=0))

arr2 = np.random.rand(1000)

print(arr2)

print(arr2.mean())
print(np.std(arr2, ddof=0))

[ 1.35812396e+00  1.86484940e+00 -7.35067980e-02 -2.49451834e-01
  1.86098472e-01  6.66972825e-01  1.39246268e+00  4.49562130e-01
  2.35378597e+00 -4.30416401e-01  9.78313108e-02 -1.95286717e+00
  1.21581208e+00 -1.67230347e+00 -1.63685364e-01  4.36755460e-01
  3.80231666e-01  8.69628727e-02  8.91015723e-01  1.09470706e+00
  1.66724797e+00 -6.37875061e-01 -2.78413967e-02 -2.82615107e+00
  5.90910497e-01  1.67627567e+00 -1.12255809e+00 -1.10414333e+00
 -2.11637584e-01  4.98375609e-01 -4.58616332e-01 -3.81383901e-01
  3.83180927e-02  5.20315600e-01  5.00454657e-01  5.89392997e-01
  1.35709664e+00  1.03682477e+00 -3.09115680e-01  2.06595834e+00
 -1.46522516e+00  4.52862042e-01 -1.46428370e+00 -4.86828213e-01
 -1.96957614e+00  8.79888498e-01 -1.53664480e+00  8.63021773e-01
 -1.96982112e-01  1.77057593e+00 -1.42910499e+00 -2.67129242e+00
 -1.66832338e+00  3.69522898e-01  1.48249248e+00 -7.48948349e-01
 -7.78417118e-01  8.06993827e-01 -8.74679244e-01 -3.89469306e-01
 -7.90235438e-01  7.04014

### [실습 3] 평균 성적 구하기


아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.


```python
# 학생별 과목 성적 데이터
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]
```

In [17]:
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

scores = np.array([scores_math, scores_english, scores_science])
print(scores)

scores_avg = np.mean(scores, axis=0)
scores_var = np.var(scores_avg)
scores_std = np.std(scores_avg)

print(scores_avg)
print(scores_var)
print(scores_std)


[[88 92 76 85 95 92 88 90 85 88]
 [90 85 80 87 92 89 83 91 86 88]
 [85 88 82 89 94 86 91 88 84 87]]
[87.66666667 88.33333333 79.33333333 87.         93.66666667 89.
 87.33333333 89.66666667 85.         87.66666667]
11.89333333333335
3.4486712417006857
